booking.property=Booling Profile Dev

spring.datasource.url=jdbc:mysql://192.168.1.71:3306/laboratorio
spring.datasource.username=laboratorio
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
