product.property=Product Profile Dev

spring.data.mongodb.uri=mongodb://admin:1234@192.168.1.71:27017/productdb?authSource=admin
spring.data.mongodb.database=productdb

# spring.data.mongodb.host=192.168.1.71
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=productdb
# spring.data.mongodb.username=admin
# spring.data.mongodb.password=1234

# logging.level.org.mongodb.driver=DEBUG
# logging.level.org.springframework.data.mongodb=DEBUG